### PR TITLE
Make sure header keys are in lowercase

### LINKED ISSUE #5: Handle uppercase headers
The `gleam-lang/http` library seem to need the headers keys to be in lowercase (https://github.com/gleam-lang/http/blob/main/src/gleam/http.gleam#L118).

But `gleam-lang/elli` does not ensure this is always the case.

For example, when running:
```bash
curl -X POST -d '{"hello":"world"}' -H 'Content-Type: application/json' http://localhost:3000
```
The code `http.get_req_header(req, "content-type")` returns `Error(Nil)`.

### PR DESCRIPTION
**Pull request by jpagex**
Here is a fix that lowercase every keys in the headers. Let me know if this solves the problem correctly for you.

Closes: #5

### CODE REVIEW

**Comment by jpagex** [comment]
The tests are failing but I do not think it is caused by my changes.

**Review by lpil — APPROVED** [review]
Thank you. Would you mind also updating the changelog?

**Comment by jpagex** [comment]
Sure. Is it OK like this?

**Review by lpil — APPROVED** [review]
Perfect!

**Pull request merged**
